### ISSUE TITLE
Switch to Gradle build system

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/psiviewer#13]
https://github.com/JetBrains/gradle-intellij-plugin seems to be the currently recommended way of building plugins for IntelliJ. Would you be interested in switching to that build system if someone would work on a PR?

**Comment by sylvanaar** [comment]
It isn't really a bad idea for this project - though it doesn't really add much value either. Psiviewer hasn't broken due to an update in years. You don't have to build it very often. It makes a lot of sense for plugins that have to target multiple versions of IDEA at the same time - on different code branches.

**Comment by sylvanaar** [comment]
I converted one of my other plugins - it has its plusses and minuses. The biggest plus is that it is easy to set up CI

**Comment by sylvanaar** [comment]
Any progress on this. I was thinking that we should do it, and if there is a PR I'd love to have it.

**Comment by Turbo87** [comment]
@sylvanaar sorry, didn't have time to work on this yet, but it's good to know that such a PR would be accepted! 👍

**Comment by hurricup** [comment]
@sylvanaar please, check the branch. Note me if it's ok for you
suppose we need a repo owner to enable CI
